SDTM_RULES_DIR = "../rules"
ADAM_RULES_DIR = "../adam_rules"
CG_CSV_PATH = "../conformance-data/CORE-RULES_GitHub Transfer Excel Tracker(SDTM and SDTMIG v2).csv"
FDA_CSV_PATH = "../conformance-data/CORE-RULES_GitHub Transfer Excel Tracker(FDA Business Rules).csv"
ADAM_CSV_PATH = "../conformance-data/ADaM Rules Tracker.csv"