name: Add Reviewers

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write
  statuses: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Add Reviewers
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const p1 = 'eljanssens';
          const p2 = 'pendingintent';
          const prAuthor = context.payload.pull_request.user.login;
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          let reviewerToAdd;

          if (prAuthor === p1) {
            reviewerToAdd = p2;
          } else if (prAuthor === p2) {
            reviewerToAdd = p1;
          } else {
            const getOpenPRCount = async (username) => {
              const response = await github.rest.search.issuesAndPullRequests({
                q: `repo:${owner}/${repo} is:pr is:open review-requested:${username}`
              });
              return response.data.total_count;
            };

            const p1Count = await getOpenPRCount(p1);
            const p2Count = await getOpenPRCount(p2);
            
            console.log(`${p1} has ${p1Count} open PRs.`);
            console.log(`${p2} has ${p2Count} open PRs.`);

            reviewerToAdd = p1Count <= p2Count ? p1 : p2;
          }

          console.log(`Assigning ${reviewerToAdd} to PR #${context.issue.number}`);

          await github.rest.pulls.requestReviewers({
            owner: owner,
            repo: repo,
            pull_number: context.issue.number,
            reviewers: [reviewerToAdd],
          });
